# Generated by Django 3.1.2 on 2020-11-01 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=80)),
                ('password', models.CharField(max_length=30)),
                ('fb_photo', models.CharField(max_length=1000)),
                ('gl_photo', models.CharField(max_length=1000)),
                ('photo_url', models.CharField(max_length=1000)),
                ('phone_number', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('lat', models.CharField(max_length=50)),
                ('lng', models.CharField(max_length=50)),
                ('registered_time', models.CharField(max_length=100)),
                ('playerID', models.CharField(max_length=300)),
                ('fcm_token', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
